### ISSUE TITLE
gm-jsse与gmssl工具不兼容

### ISSUE THREAD

**Issue by idtaichangle** [aliyun/gm-jsse#74]
有个开源国密工具gmssl，https://github.com/guanzhi/GmSSL/tree/GmSSL-v2。（注意是v2分支）。
这个工具与openssl兼容，可以生成国密自签名证书，也可以作为国密服务端或客户端。

我用gm-jsse作了服务端，启动了com.aliyun.gmsse.server.ClientTest的testServer
（代码有一处改动：com.aliyun.gmsse.server.Server里面改了ss.setNeedClientAuth(false);）

我用这个工具作为客户端连接gm-jsse服务端，
`gmssl s_client -connect 127.0.0.1:8443 -gmtls`
发现报以下错误。

`javax.net.ssl.SSLException: decrypt pre master secret failed
	at com.aliyun.gmsse.protocol.ServerConnectionContext.receiveClientKeyExchange(ServerConnectionContext.java:192)
	at com.aliyun.gmsse.protocol.ServerConnectionContext.kickstart(ServerConnectionContext.java:96)
	at com.aliyun.gmsse.GMSSLSocket.startHandshake(GMSSLSocket.java:215)
	at com.aliyun.gmsse.GMSSLSocket$AppDataInputStream.read(GMSSLSocket.java:310)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.aliyun.gmsse.server.ClientTest$1.run(ClientTest.java:48)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid point coordinates
	at org.bouncycastle.math.ec.ECCurve.validatePoint(Unknown Source)
	at org.bouncycastle.math.ec.ECCurve.decodePoint(Unknown Source)
	at org.bouncycastle.crypto.engines.SM2Engine.decrypt(Unknown Source)
	at org.bouncycastle.crypto.engines.SM2Engine.processBlock(Unknown Source)
	at com.aliyun.gmsse.crypto.Crypto.decrypt(Crypto.java:100)
	at com.aliyun.gmsse.protocol.ServerConnectionContext.receiveClientKeyExchange(ServerConnectionContext.java:190)
	... 12 more
`
可以解决一下这个问题吗？

**Comment by JacksonTian** [comment]
请用最新的版本测试一下
